---
file_name: CHANGELOG.md.new
excluded_labels:
  - maintenance
  - dependencies
sections:
  added:
    - feature
    - new feature
  changed:
    - backwards-incompatible
    - depricated
  fixed:
    - bug
    - bugfix
    - enhancement
    - fix
    - fixed
skip_entries_without_label: false
show_unreleased: true
check_for_updates: true
logger: console
