# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  -
    ldflags:
      - -s -w -X "main.version={{.Env.RELEASE_VERSION}}"
    main: main.go
    binary: tfswitch
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm64    
checksum:
  name_template: '{{ .ProjectName }}_{{.Env.RELEASE_VERSION}}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

archives:
  - id: archives
    name_template: >-
      {{- .ProjectName }}_
      {{.Env.RELEASE_VERSION}}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}


brews:
  -
    # Name of the recipe
    # Default to project name
    name: tfswitch

  # GitHub/GitLab repository to push the formula to
    # Gitea is not supported yet, but the support coming
    repository:
      owner: warrensbox
      name: homebrew-tap
      token: "{{ .Env.PERSONAL_ACCESS_TOKEN }}"

    # Reporitory to push the tap to.
    # github:
    #   owner: warrensbox
    #   name: homebrew-tap

    # Allows you to set a custom download strategy.
    # Default is empty.
    #download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: Warren Veerasingam
      email: warren.veerasingam@gmail.com

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Caveats for the user of your binary.
    # Default is empty.
    caveats: "Type 'tfswitch' on your command line and choose the terraform version that you want from the dropdown. This command currently only works on macOS and Linux"

    # Your app's homepage.
    # Default is empty.
    homepage: "https://warrensbox.github.io/terraform-switcher"

    # Your app's description.
    # Default is empty.
    description: "The tfswitch command lets you switch between terraform versions."

    # Packages that conflict with your package.
    conflicts:
      - terraform

    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # Default is false.
    skip_upload: false

    # So you can `brew test` your formula.
    # Default is empty.
    test: |
      system "#{bin}/tfswitch --version"
    # Custom install script for brew.
    # Default is 'bin.install "program"'.
    install: |
      bin.install "tfswitch"
