name: tfswitch
version: '0.10.958'
summary: A command line tool to switch between different versions of terraform
description: |
  The `tfswitch` command line tool lets you switch between different versions of terraform(https://www.terraform.io/).
  If you do not have a particular version of terraform installed, `tfswitch` will download the version you desire.
  The installation is minimal and easy.
  Once installed, simply select the version you require from the dropdown and start using terraform.
architectures:
  - build-on: [amd64,arm64]
    run-on: [amd64,arm64]
assumes: [snapd2.45]
base: core18
 
grade: stable
confinement: strict
 
apps:
  tfswitch:
    command: bin/tfswitch
    plugs:
      - home
      - network
      - network-bind
      
parts:
  tfswitch:
    source: .
    plugin: go
    go-importpath: github.com/warrensbox/terraform-switcher
    build-packages: [gcc, g++, make]
    go-buildtags:
      - tfswitch
    override-build: 
      VER=$(git ls-remote --tags git://github.com/warrensbox/terraform-switcher | awk '{print $2}'| awk -F"/" '{print $3}' | sort -n -t. -k1,1 -k2,2 -k3,3 | tail -n 2 | head -n1)
      go build  -v -ldflags "-X main.version=0.10.958"  -o ../install/bin/tfswitch