source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
gem "minima"

gem "commonmarker"

gem "ffi", ">= 1.9.24"
gem "rubyzip", ">= 1.2.2"
gem "jekyll", ">= 3.7.4"
gem "nokogiri", ">= 1.8.5"